// : Generated by xaf-index-generator :

export { default as IconArrow } from './icon.arrow.vue'
export { default as IconClose } from './icon.close.vue'
export { default as IconEdit } from './icon.edit.vue'
export { default as IconHome } from './icon.home.vue'
export { default as IconLogout } from './icon.logout.vue'
export { default as IconSetup } from './icon.setup.vue'
export { default as IconTeam } from './icon.team.vue'
