// : Generated by xaf-index-generator :

export { default as IconHome } from './icon.home.vue'
export { default as IconSetup } from './icon.setup.vue'
export { default as IconTeam } from './icon.team.vue'